use_frameworks!

target 'CPSegmentedScrollView_Example' do
  pod 'CPSegmentedScrollView', :path => '../'

  target 'CPSegmentedScrollView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
