use_frameworks!

target 'CPSegmentedScrollView_Example' do
  pod 'CPSegmentedScrollView', :path => '../'

  target 'CPSegmentedScrollView_Tests' do
    inherit! :search_paths

    pod 'OCMockito'
  end
  
  target 'CPSegmentedScrollView_ExampleUITests' do
    inherit! :search_paths
  end
end
