osx_image: xcode8
language: objective-c
cache: cocoapods
podfile: Example/Podfile
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - LANGUAGE=en_US.UTF-8
before_install:
  - gem install cocoapods --pre # Since Travis is not always on latest version
  - gem update xcpretty
  - gem cleanup
  - pod install --project-directory=Example
branches:
  only: 
    - master
    - develop
script:
  - set -o pipefail
  - xcodebuild test -workspace Example/CPSegmentedScrollView.xcworkspace -scheme CPSegmentedScrollView-Example -sdk iphonesimulator -destination "name=iPhone SE" | tee xcodebuild.log | xcpretty
  - pod lib lint
after_failure:
  - echo "***"
  - echo "xcodebuild log"
  - cat -n xcodebuild.log
  - echo "***"
  - echo "session log"
  - cat -n $TMPDIR/com.apple.dt.XCTest-status/Session*.log
  - echo "***"
  - echo "test log"
  - cat -n ~/Library/Logs/DiagnosticReports/xctest*.crash  
  - echo "***"
notifications:
  email:
    recipients:
      - $CP_EMAIL_ADDRESS
    on_success: never
    on_failure: always